spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    sql:
        init:
            mode: never
    jpa:
        # Choose either MySQL 8 or MySQL 5 below
        # For MySQL 8
        database-platform: org.hibernate.dialect.MySQL8Dialect
        #    #For MySQL 5
        #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
mail:
    host: in-v3.mailjet.com
    port: 587
    username: "886c49df72c6b28374754d15a0a844db"
    password: "248ea8cc8074d8976e38ea7e22d697cc"
    properties:
        mail:
            debug: true
            smtp:
                auth: true
                starttls:
                    enable: true
#mobile:
#    admin:
#        defaultpass: ${DEFAULT_PASS:test}