spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: ${MYSQL_URL}
        username: ${MYSQLUSER}
        password: ${MYSQLPASSWORD}
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    sql:
        init:
            mode: never
    jpa:
        # Choose either MySQL 8 or MySQL 5 below
        # For MySQL 8
        database-platform: org.hibernate.dialect.MySQL8Dialect
        #    #For MySQL 5
        #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
mail:
    host: in-v3.mailjet.com
    port: 587
    username: ${MAIL_API_KEY}
    password: ${MAIL_API_SECRET}
    properties:
        mail:
            debug: true
            smtp:
                auth: true
                starttls:
                    enable: true
#mobile:
#    admin:
#        defaultpass: ${DEFAULT_PASS:test}